// Generated by build-installers.ps1 from Cargo.toml. DO NOT EDIT.
// setup.c uses PLUGINVERSION for the -setup-plugin-version argument,
// setup.rc uses the four numeric parts for FILEVERSION / PRODUCTVERSION.
#define PLUGINMAJOR		1
#define PLUGINMINOR		3
#define PLUGINREVISION	0
#define PLUGINBUILD		0

#define PLUGINVERSION	"1.3.0.0"
