// Generated by build-installers.ps1 from Cargo.toml. DO NOT EDIT.
// setup.c uses PLUGINVERSION for the -setup-plugin-version argument,
// setup.rc uses the four numeric parts for FILEVERSION / PRODUCTVERSION.
#define PLUGINMAJOR		1
#define PLUGINMINOR		1
#define PLUGINREVISION	11
#define PLUGINBUILD		0

#define PLUGINVERSION	"1.1.11.0"
