<#
.SYNOPSIS
  一键打包 everything-mcp 的 x86 / x64 安装程序。
.DESCRIPTION
  打包方式与 voidtools 官方插件（http_server / etp_server）完全一致：

    1. cargo 分别构建 x64 与 i686 两个 DLL；
    2. 各自 bzip2 压缩成 setup.dll.bz2（优先 7-Zip，没有则用 Python 的 bz2 模块）；
    3. rc.exe 把 setup.dll.bz2 以 IDR_DLL_BZ2 RCDATA 编进 PE 资源；
    4. cl.exe 编译链接 setup\setup.c，产出两个自包含的 setup.exe。

  生成的 setup.exe 自身不拷贝任何文件：运行后它先找到 Everything.exe
  （注册表 ExePath -> 正在运行的实例 -> 手动浏览），再用 -setup-plugin
  系列参数重新拉起 Everything，由 Everything 自己解压安装插件，之后可在
  Everything 选项 -> 插件 里一键卸载，与官方插件体验一致。

  产物：installer\dist\everything-mcp-<版本>-x64-setup.exe
        installer\dist\everything-mcp-<版本>-x86-setup.exe

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File build-installers.ps1
.EXAMPLE
  powershell -ExecutionPolicy Bypass -File build-installers.ps1 -SkipBuild
#>
[CmdletBinding()]
param(
    # 跳过 cargo build，直接用 target\ 下已有的 DLL（只改 setup.c 后单独重编时有用）
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'

$InstallerDir = $PSScriptRoot
$RepoRoot     = Split-Path -Parent $InstallerDir
$SetupSrcDir  = Join-Path $InstallerDir 'setup'
$BuildRoot    = Join-Path $InstallerDir 'build'
$DistDir      = Join-Path $InstallerDir 'dist'

# ---------------------------------------------------------------------
# 版本号：单一来源是 Cargo.toml，每次打包同步生成 setup\version.h
# ---------------------------------------------------------------------
$cargoToml = Get-Content -Raw -LiteralPath (Join-Path $RepoRoot 'Cargo.toml')
$Version = [regex]::Match($cargoToml, '(?m)^version\s*=\s*"([^"]+)"').Groups[1].Value
if (-not $Version) { throw 'Cargo.toml 中未找到 version' }
$v = ($Version -split '\.')
while ($v.Count -lt 4) { $v += '0' }

$versionH = @"
// Generated by build-installers.ps1 from Cargo.toml. DO NOT EDIT.
// setup.c uses PLUGINVERSION for the -setup-plugin-version argument,
// setup.rc uses the four numeric parts for FILEVERSION / PRODUCTVERSION.
#define PLUGINMAJOR		$($v[0])
#define PLUGINMINOR		$($v[1])
#define PLUGINREVISION	$($v[2])
#define PLUGINBUILD		$($v[3])

#define PLUGINVERSION	"$Version.0"
"@
# rc.exe 要求 CRLF 行尾、且文件必须以换行结束，否则报 RC1004（unexpected end of file）
$versionH = ($versionH -replace "`r?`n", "`r`n") + "`r`n"
[IO.File]::WriteAllText((Join-Path $SetupSrcDir 'version.h'), $versionH, (New-Object Text.UTF8Encoding $false))
Write-Host "版本号：$Version（已同步 setup\version.h）"

# ---------------------------------------------------------------------
# 工具链定位：Visual Studio 安装根、cl.exe（x64 与 x86 交叉）、rc.exe、bz2 压缩器
# ---------------------------------------------------------------------
function Get-VsInstalls {
    # 返回所有候选的 Visual Studio 安装根目录（vswhere 优先，其次通配 Program Files）
    $found = @()

    $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    if (Test-Path -LiteralPath $vswhere) {
        $inst = & $vswhere -products '*' -all -property installationPath 2>$null
        foreach ($i in $inst) { if ($i) { $found += $i.Trim() } }
    }

    foreach ($root in @($env:ProgramFiles, ${env:ProgramFiles(x86)})) {
        $c = Join-Path $root 'Microsoft Visual Studio'
        if (-not (Test-Path -LiteralPath $c)) { continue }
        $found += (Get-ChildItem -LiteralPath $c -Directory -ErrorAction SilentlyContinue).FullName
    }

    return $found
}

function Find-MsvcHostx64 {
    # 返回 MSVC 的 bin\Hostx64 目录（同时提供 x64 目标与 x86 交叉编译的 cl.exe）
    foreach ($vs in (Get-VsInstalls)) {
        $tools = Join-Path $vs 'VC\Tools\MSVC'
        if (-not (Test-Path -LiteralPath $tools)) { continue }
        $d = Get-ChildItem -LiteralPath $tools -Directory -ErrorAction SilentlyContinue |
             Sort-Object Name -Descending |
             Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName 'bin\Hostx64\x64\cl.exe') } |
             Select-Object -First 1
        if ($d) { return (Join-Path $d.FullName 'bin\Hostx64') }
    }
    return $null
}

function Find-Rc {
    $sdkBin = 'C:\Program Files (x86)\Windows Kits\10\bin'
    if (Test-Path -LiteralPath $sdkBin) {
        $rc = Get-ChildItem -LiteralPath $sdkBin -Directory -ErrorAction SilentlyContinue |
              Sort-Object Name -Descending |
              ForEach-Object { Join-Path $_.FullName 'x64\rc.exe' } |
              Where-Object { Test-Path -LiteralPath $_ } |
              Select-Object -First 1
        if ($rc) { return $rc }
    }
    return (Get-Command rc.exe -ErrorAction SilentlyContinue).Source
}

$msvcHost = Find-MsvcHostx64
if (-not $msvcHost) { throw '未找到 MSVC 工具链（cl.exe）。请安装 Visual Studio（含“使用 C++ 的桌面开发”工作负载）' }
$ClX64 = Join-Path $msvcHost 'x64\cl.exe'
$ClX86 = Join-Path $msvcHost 'x86\cl.exe'
foreach ($c in @($ClX64, $ClX86)) {
    if (-not (Test-Path -LiteralPath $c)) { throw "缺少编译器：$c" }
}

# 从 ...\VC\Tools\MSVC\<ver>\bin\Hostx64 往上 6 级得到 VS 安装根，取 VsDevCmd
$vsInstall = $msvcHost
1..6 | ForEach-Object { $vsInstall = Split-Path -Parent $vsInstall }
$VsDevCmd = Join-Path $vsInstall 'Common7\Tools\VsDevCmd.bat'
if (-not (Test-Path -LiteralPath $VsDevCmd)) { throw "找不到 $VsDevCmd" }

$Rc = Find-Rc
if (-not $Rc) { throw '未找到 rc.exe。请安装 Windows SDK' }

$SevenZip = @("$env:ProgramFiles\7-Zip\7z.exe", "${env:ProgramFiles(x86)}\7-Zip\7z.exe") |
            Where-Object { Test-Path -LiteralPath $_ } | Select-Object -First 1
$Python = (Get-Command python -ErrorAction SilentlyContinue).Source
if (-not $SevenZip -and -not $Python) { throw '未找到 7-Zip 或 Python，无法生成 setup.dll.bz2' }
$bz2Tool = if ($SevenZip) { "7-Zip ($SevenZip)" } else { "Python bz2 ($Python)" }

Write-Host "cl.exe (x64) : $ClX64"
Write-Host "cl.exe (x86) : $ClX86"
Write-Host "rc.exe       : $Rc"
Write-Host "bz2 压缩器   : $bz2Tool"

function Import-VsDevEnv {
    param([string]$Arch)   # amd64 或 x86（目标架构）
    # 裸调 cl.exe 会报 C1034（windows.h: 不包括路径集），
    # 必须先由 VsDevCmd 把 INCLUDE / LIB / LIBPATH / PATH 注入当前进程。
    $out = & cmd /c "`"$VsDevCmd`" -arch=$Arch -host_arch=amd64 >nul && set"
    foreach ($line in $out) {
        if ($line -match '^(INCLUDE|LIB|LIBPATH|PATH)=(.*)$') {
            Set-Item -Path ("env:" + $matches[1]) -Value $matches[2]
        }
    }
}

# ---------------------------------------------------------------------
# 确保 i686 目标已安装
# ---------------------------------------------------------------------
if (-not $SkipBuild) {
    $installed = @(& rustup target list --installed 2>$null | ForEach-Object { $_.Trim() })
    if ($installed -notcontains 'i686-pc-windows-msvc') {
        Write-Host '== 添加 rustup 目标 i686-pc-windows-msvc ==' -ForegroundColor Cyan
        & rustup target add i686-pc-windows-msvc
        if ($LASTEXITCODE -ne 0) { throw 'rustup target add i686-pc-windows-msvc 失败' }
    }
}

# ---------------------------------------------------------------------
# 单个架构的完整打包流程
# ---------------------------------------------------------------------
function Build-Setup {
    param([hashtable]$Arch)

    $tag = $Arch.Tag
    $work = Join-Path $BuildRoot $tag
    $dllSrc = if ($Arch.Target) {
        Join-Path $RepoRoot "target\$($Arch.Target)\release\everything_mcp.dll"
    } else {
        Join-Path $RepoRoot 'target\release\everything_mcp.dll'
    }

    Write-Host "`n== [$tag] 构建插件 DLL ==" -ForegroundColor Cyan
    if ($SkipBuild) {
        if (-not (Test-Path -LiteralPath $dllSrc)) { throw "-SkipBuild 但找不到 $dllSrc" }
    } else {
        $cargoArgs = @('build', '--release')
        if ($Arch.Target) { $cargoArgs += @('--target', $Arch.Target) }
        & cargo @cargoArgs
        if ($LASTEXITCODE -ne 0) { throw "cargo build ($tag) 失败" }
    }
    if (-not (Test-Path -LiteralPath $dllSrc)) { throw "未生成 $dllSrc" }

    # 干净的工作目录：rc.exe 的 RCDATA 相对路径和 #include 都按工作目录解析
    Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path $work   | Out-Null
    New-Item -ItemType Directory -Force -Path $DistDir | Out-Null

    $dll = Join-Path $work $Arch.Dll
    Copy-Item -LiteralPath $dllSrc -Destination $dll -Force
    Write-Host "[$tag] $($Arch.Dll) $((Get-Item -LiteralPath $dll).Length) 字节"

    # bzip2 压缩（官方 build32/64.bat 用 7-Zip，这里 7-Zip 优先、Python 兜底）
    $bz2 = Join-Path $work 'setup.dll.bz2'
    Write-Host "== [$tag] 压缩 setup.dll.bz2 ==" -ForegroundColor Cyan
    if ($SevenZip) {
        & $SevenZip a -tbzip2 -mx=9 $bz2 $dll | Out-Null
        if ($LASTEXITCODE -ne 0) { throw "7-Zip 压缩失败 ($tag)" }
    } else {
        $py = 'import bz2,sys;d=open(sys.argv[1],''rb'').read();open(sys.argv[2],''wb'').write(bz2.compress(d,9))'
        & $Python -c $py $dll $bz2
        if ($LASTEXITCODE -ne 0) { throw "Python bz2 压缩失败 ($tag)" }
    }
    Write-Host "[$tag] setup.dll.bz2 $((Get-Item -LiteralPath $bz2).Length) 字节"

    # 源码进工作目录，保证 rc.exe / cl.exe 的一切相对路径都在这里解析；
    # 同时统一成 CRLF 行尾（MSVC 工具链的原生约定）
    foreach ($f in @('setup.c', 'setup.rc', 'resource.h', 'version.h')) {
        $text = [IO.File]::ReadAllText((Join-Path $SetupSrcDir $f))
        [IO.File]::WriteAllText((Join-Path $work $f), ($text -replace "`r?`n", "`r`n"), (New-Object Text.UTF8Encoding $false))
    }

    $cl = if ($tag -eq 'x86') { $ClX86 } else { $ClX64 }
    $outName = "everything-mcp-$Version-$tag-setup.exe"
    Import-VsDevEnv -Arch $(if ($tag -eq 'x86') { 'x86' } else { 'amd64' })

    Push-Location $work
    try {
        Write-Host "== [$tag] rc.exe 编译资源 ==" -ForegroundColor Cyan
        & $Rc /nologo /fo setup.res setup.rc
        if ($LASTEXITCODE -ne 0) { throw "rc.exe 失败 ($tag)" }

        Write-Host "== [$tag] cl.exe 编译链接 ==" -ForegroundColor Cyan
        # /Fe 用相对名，产物先落工作目录，最后再复制到 dist（避开路径带空格的问题）
        & $cl /nologo /O2 /MT /W3 /DNDEBUG /DWIN32 /D_WINDOWS /Fosetup.obj /Fesetup.exe setup.c setup.res /link /nologo /subsystem:windows psapi.lib shell32.lib ole32.lib advapi32.lib user32.lib
        if ($LASTEXITCODE -ne 0) { throw "cl.exe 失败 ($tag)" }

        $out = Join-Path $DistDir $outName
        Copy-Item -LiteralPath (Join-Path $work 'setup.exe') -Destination $out -Force
        Write-Host "[$tag] 生成 $out（$((Get-Item -LiteralPath $out).Length) 字节）" -ForegroundColor Green
    } finally {
        Pop-Location
    }
}

# ---------------------------------------------------------------------
# 两个架构各跑一遍
# ---------------------------------------------------------------------
$archs = @(
    @{ Tag = 'x64'; Target = $null;                  Dll = 'everything_mcp64.dll' }
    @{ Tag = 'x86'; Target = 'i686-pc-windows-msvc'; Dll = 'everything_mcp32.dll' }
)

foreach ($a in $archs) { Build-Setup -Arch $a }

Write-Host "`n全部完成，产物在 $DistDir ：" -ForegroundColor Green
Get-ChildItem -LiteralPath $DistDir -Filter 'everything-mcp-*-setup.exe' | Sort-Object Name |
    ForEach-Object { Write-Host ("  {0}  {1:N0} 字节" -f $_.Name, $_.Length) }
